name: Continuous integration
on: [pull_request, push]

jobs:
  build-simulator-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator TARGET=android
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-simulator-android.apk
          path: output/release/simulator/android/app/outputs/apk/release/android-release-unsigned.apk
  build-device-n0100:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@v1
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 MODEL=n0100 epsilon.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.update.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.beta.dfu
      - run: make -j2 MODEL=n0100 flasher.light.dfu
      - run: make -j2 MODEL=n0100 flasher.verbose.dfu
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-device-n0100.dfu
          path: output/release/device/n0100/epsilon.dfu
      - run: make -j2 MODEL=n0100 test.elf
  build-device-n0110:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@v1
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 epsilon.dfu
      - run: make -j2 epsilon.onboarding.dfu
      - run: make -j2 epsilon.onboarding.update.dfu
      - run: make -j2 epsilon.onboarding.beta.dfu
      - run: make -j2 flasher.light.dfu
      - run: make -j2 flasher.verbose.dfu
      - run: make -j2 bench.ram.dfu
      - run: make -j2 bench.flash.dfu
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-device-n0110.dfu
          path: output/release/device/n0110/epsilon.dfu
      - run: make -j2 test.elf
  build-simulator-web:
    runs-on: ubuntu-latest
    steps:
      - uses: numworks/setup-emscripten@v1
        with:
          sdk: latest-fastcomp
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator TARGET=web
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-simulator-web.zip
          path: output/release/simulator/web/epsilon.zip
      - run: make -j2 PLATFORM=simulator TARGET=web test.headless.js
  build-simulator-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-simulator-linux.bin
          path: output/release/simulator/linux/epsilon.bin
      - run: make -j2 PLATFORM=simulator test.headless.bin
